# Generated by Django 4.1.7 on 2023-04-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_booking', models.DateField()),
                ('room', models.IntegerField(default=0)),
                ('date_of_residence', models.DateField()),
                ('amount_of_residents', models.IntegerField(default=0)),
                ('phone_number', models.IntegerField(default=0)),
            ],
        ),
    ]
