# Generated by Django 4.1.7 on 2023-04-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='date_of_booking',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='date_of_residence',
            field=models.CharField(max_length=30),
        ),
    ]
