# Generated by Django 4.1.7 on 2023-04-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_bookings_date_of_booking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='dates_of_rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room1', models.CharField(blank=True, max_length=5000)),
                ('room2', models.CharField(blank=True, max_length=5000)),
                ('room3', models.CharField(blank=True, max_length=5000)),
                ('room4', models.CharField(blank=True, max_length=5000)),
                ('room5', models.CharField(blank=True, max_length=5000)),
            ],
        ),
    ]
