# Generated by Django 4.1.7 on 2023-04-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_dates_of_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dates_of_rooms',
            name='room1',
        ),
        migrations.RemoveField(
            model_name='dates_of_rooms',
            name='room2',
        ),
        migrations.RemoveField(
            model_name='dates_of_rooms',
            name='room3',
        ),
        migrations.RemoveField(
            model_name='dates_of_rooms',
            name='room4',
        ),
        migrations.RemoveField(
            model_name='dates_of_rooms',
            name='room5',
        ),
        migrations.AddField(
            model_name='dates_of_rooms',
            name='rooms',
            field=models.JSONField(default='{}'),
        ),
    ]
